### ISSUE TITLE
Error during division

### ISSUE THREAD

**Issue by u4294967296** [HrushikeshPawar/Sexagesimal-Calculator#2]
Hi, it seems there is a bug in "Division" method.
To reproduce, run: Sexagesimal.Division(2, 1)
Result: AttributeError: 'Sexagesimal' object has no attribute 'split'
To fix it I just commented out lines 997-1003 in file "sexagesimal.py". The variable B_Num_R is not used in the code later anyway.
Thanks for the calculator. I ran the Babylonian method to find the square root (just for fun), and with your library I did it in sexagesimal system. After 4 iterations the result is 01;24,51,10 - the same as on the famous "Babylonian clay tablet YBC 7289":)

**Comment by HrushikeshPawar** [comment]
Hey,

Thanks for your observations.
I will surely go through my whole code again and make necessary changes. I guess it time to refactor the code.
And I am glad that you found this library useful
